Papyrillio\BeehiveBundle\Entity\Correction:
    type: entity
    table: correction
    gedmo:
        loggable
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        source:
            type: integer
            nullable: true
        text:
            type: string
            length: 64
        tm:
            type: integer
            nullable: true
        hgv:
            type: string
            length: 64
            nullable: true
        ddb:
            type: string
            length: 64
            nullable: true
        collection:
            type: string
            length: 64
            nullable: true
        volume:
            type: string
            length: 64
            nullable: true
        document:
            type: string
            length: 64
            nullable: true
        position:
            type: text
            nullable: true
            gedmo:
                - versioned
        description:
            type: text
            gedmo:
                - versioned
        compilationPage:
            name: compilation_page
            type: string
            length: 64
            nullable: true
        status:
            type: text
            gedmo:
                - versioned
        creator:
            type: text
        created:
            type: datetime
        sortPage:
            name: sort_page
            type: integer
            nullable: true
        sortSide:
            name: sort_side
            type: string
            length: 2
            nullable: true
        sortFragment:
            name: sort_fragment
            type: string
            nullable: true
        sortColumn:
            name: sort_column
            type: string
            length: 8
            nullable: true
        sortLine:
            name: sort_line
            type: integer
            nullable: true
        sortSystem:
            name: sort_system
            type: string
            length: 256
        sortUser:
            name: sort_user
            type: string
            length: 256
            nullable: true
        sort:
            type: string
            length: 256
    manyToOne:
        edition:
            targetEntity: Edition
            inversedBy: corrections
            joinColumn:
                name: edition_id
                referencedColumnName: id
                nullable: false

        compilation:
            targetEntity: Compilation
            inversedBy: corrections
            joinColumn:
                name: compilation_id
                referencedColumnName: id
                nullable: false
    oneToMany:
        tasks:
            targetEntity: Task
            mappedBy: correction
        indexEntries:
            targetEntity: IndexEntry
            mappedBy: correction
    manyToMany:
        registerEntries:
            targetEntity: Register
            joinTable:
              name: correction_register
              joinColumns:
                correction_id:
                  referencedColumnName: id
              inverseJoinColumns:
                register_id:
                  referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [ encode ]
        postPersist: [ decode ]
        preUpdate: [ encode ]
        postUpdate: [ decode ]
        postLoad: [ decode ]
        onFlush: [ encode ]

    # don't forget to init the collection in entity __construct() method